export const ipcChannels = {
  getRuntimeInfo: 'runtime:get-info',
  getPinnedGroupOpen: 'preferences:get-pinned-group-open',
  getProjectGroupOpen: 'preferences:get-project-group-open',
  getSidebarOpen: 'preferences:get-sidebar-open',
  getSidebarWidth: 'preferences:get-sidebar-width',
  getTheme: 'preferences:get-theme',
  setPinnedGroupOpen: 'preferences:set-pinned-group-open',
  setProjectGroupOpen: 'preferences:set-project-group-open',
  setSidebarOpen: 'preferences:set-sidebar-open',
  setSidebarWidth: 'preferences:set-sidebar-width',
  setTheme: 'preferences:set-theme',
  addProjectDirectory: 'projects:add-directory',
  getWorkspaceNavigation: 'projects:get-navigation',
  selectWorkspace: 'projects:select-workspace',
  getDefaultShell: 'shells:get-default',
  listShells: 'shells:list',
  setDefaultShell: 'shells:set-default',
  createTerminal: 'terminals:create',
  writeTerminal: 'terminals:write',
  resizeTerminal: 'terminals:resize',
  closeTerminal: 'terminals:close',
  terminalData: 'terminals:data',
  terminalExit: 'terminals:exit',
  getWorkspaceLayout: 'workspace-layouts:get',
  saveWorkspaceLayout: 'workspace-layouts:save',
} as const
